### ISSUE TITLE
TypeError: VerEx.sanitize is not a function

### ISSUE THREAD

**Issue by amoshydra** [VerbalExpressions/JSVerbalExpressions#175]
## Current Problem
sanitize is not available as a static function as documented in here
https://verbalexpressions.github.io/JSVerbalExpressions/VerbalExpression/utilities

VerEx.sanitize is `undefined`

Reproduce link: https://codesandbox.io/s/0437l1r9jl

## Expected behaviour

I was expected to use VerEx sanitize function like this
```js
const filePath = '/path/to/file'
const sanitized = VerEx.sanitize(filePath)
sanitized.source === ///path//to//file/.source
```

## Environment
Version tested:
  - v0.3.0
  - https://github.com/shreyasminocha/JSVerbalExpressions/commit/5ca909d147ec9c9f61db9de30f1f3250ccf79ab3

**Comment by shreyasminocha** [comment]
I am almost sure #174 would fix this. Could you please try?

**Comment by shreyasminocha** [comment]
This is because the `sanitize` method is a static method of the `VerbalExpression` class. However, we are export only an instance of VerbalExpression ([per this](https://github.com/shreyasminocha/JSVerbalExpressions/blob/5ca909d147ec9c9f61db9de30f1f3250ccf79ab3/dist/verbalexpressions.js#L665-L671)). Not sure what the way forward is.

**Comment by shreyasminocha** [comment]
If there'x enough use-case, LGTM; @jehna, @ionutvmi?

**Comment by jehna** [comment]
Hmm. The documentation actually points to `VerbalExpressions.sanitize` (there's a typo, it should be `VerbalExpression.sanitize`). At the moment we don't expose the main `VerbalExpressions` class at all to the public.

I checked the previous versions (0.2.0, 0.2.1 and 0.1.2), and seems that we haven't exposed the main class at any point 🤔 

What did work in 0.2.x however was the format `VerEx().sanitize(input)`.

I'd propose that we'd think this from the public API's standpoint: I'd think the most logical way would be to use:

```
import { sanitize } from 'verbal-expressions'

sanitize(input)
```

We could then use the es import/exports to export the sanitize function:

```
export function sanitize(...) {...}
```

...and use the function instead of the [static `VerbalExpression.sanitize`](https://github.com/VerbalExpressions/JSVerbalExpressions/blob/master/VerbalExpressions.js#L108) in the code. How does this sound?

**Comment by shreyasminocha** [comment]
@jehna Yeah, I noticed the typo too (will open a PR).

Sounds good to me, but it's just that es import/export are annoying to transpile. Even with `babel-plugin-transform-es2015-modules-umd`, there's the issue of having to add `.default` at the end of the exported global when using the transpiled version. `babel-plugin-add-module-exports` doesn't work with anything except CommonJS. I might create my own babel plugin to fix this, but till then we'll have to do it the ES5 way.

**Comment by jehna** [comment]
@shreyasminocha alright, using `VerEx.sanitize = VerbalExpression.sanitize;` sounds good 🙂👍 Simple and works!

**Comment by shreyasminocha** [comment]
#181 fixes this.
