### ISSUE TITLE
multiple on special characters

### ISSUE THREAD

**Issue by lukas-dachtler** [VerbalExpressions/JSVerbalExpressions#183]
Hi,
I think it's not possible to use the special characters together with mutlitple. Is that a bug?

I expected the following to work, but it gives a TypeError:
`exp.find('<a').whitespace().multiple().then('>')`
Wrapping the whitespace in a group didn't help either.

I tried it in other ways but then I got some interesting results:
`exp.find('<a').then('\s*').then('>')`
This actually returns: `/(?:<head)(?:s\*)(?:>)/gm` _(notice the switched backslash)_
And:
`exp.find('<a').add('\s*').then('>')` actually requires a double slash `\\s*` in the add method.

Can someone help me out please? What is the correct way to check for 0 or more whitespaces?
Ps.: Sorry if I'm missing something obvious here.

**Comment by shreyasminocha** [comment]
Hi. `.whitespace()` matches one or more whitespace characters, rather than a single one.

With your second example, `.then` matches only literal characters, you can't use it to add regex pieces. Yes, with `.add` you will need to escape the backslash before `s` because otherwise js will interpret `\s` as an escaped `s`.

You can check for one or more whitespace characters with `.whitespace`.

**Comment by lukas-dachtler** [comment]
Thanks for the fast reply and the explanation of `.then` and `.add`.
`exp.find('<a').whitespace().multiple().then('>')` gives me `TypeError: e is undefined`

That's my full code:
`const exp = VerEx();
exp.find('<a').whitespace().multiple().then('>');
console.log(exp.test('<a  >'));`

**Comment by lukas-dachtler** [comment]
Yep, with this version it's working.

**Comment by lukas-dachtler** [comment]
Thanks again for your great help @shreyasminocha! :+1:
I'll check back later in the day after the PR is through and will then update back to the newest version in my project.
