### ISSUE TITLE
returning false for the given example test on Firefox Nightly (v30) & Chrome 32.0.1700.107

### ISSUE THREAD

**Issue by cybernetics** [VerbalExpressions/JSVerbalExpressions#74]
![ff30-test-fail](https://f.cloud.github.com/assets/79887/2125075/1c1a4dbe-924b-11e3-83ce-a1c0cbcb955c.png)

**Comment by ionutvmi** [comment]
Well this is more then an year old but better late then never :smile: .

This is the expected behavior for a regex with the `g` flag.
When `test()` is called on a regular expression with the `g` flag it sets the lastIndex property of the regular expression object to the character position immediately following the matched sub-string.
When we call it the second time it begins the search from the specified `lastIndex`. If no match is found it will return false and the lastIndex property is set back to 0.

Here we have some code to better understand this:

```js
var reg = /fn/g;
reg.test('hello') // => false
reg.lastIndex // => 0
reg.test('some fn text') // => true
reg.lastIndex // => 7
reg.test('some fn text') // => false
reg.lastIndex // => 0
reg.test('some fn text fn me me') // => true
reg.test('some fn text fn me me') // => true
reg.test('some fn text fn me me') // => false
```

If you need to prevent this you can set the `lastIndex` property back to 0 at any time.

[MDN RegExp.lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex).

**Comment by ionutvmi** [comment]
Closing this one as this is the expected behavior.
